version: '3'
services:
  customer:
    build: ./customers
    ports:
      - 3301:3301
    depends_on:
      - seed
  
  gateway:
    build: ./gateway
    ports:
      - 3300:3300
    depends_on:
      - seed

  product:
    build: ./products
    ports:
      - 3302:3302
    depends_on:
      - seed
  
  payment:
    build: ./payments
    ports:
      - 3304:3304
    depends_on:
      - seed
  
  order:
    build: ./orders
    ports:
      - 3303:3303
    depends_on:
      - seed

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  seed:
    build: ./mongodb
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitMQ
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "test"
        RABBITMQ_DEFAULT_PASS: "test"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672